import { useState, useEffect, useCallback } from 'react';

export interface LastFmTrack {
    name: string;
    artist: string;
    album: string;
    image: string;
    url: string;
    nowPlaying: boolean;
    timestamp?: number;
    timeAgo: string;
}

export interface LastFmData {
    currentTrack: LastFmTrack | null;
    recentTracks: LastFmTrack[];
    totalScrobbles: string;
    isLoading: boolean;
    error: string | null;
    isNowPlaying: boolean;
    refresh: () => Promise<void>;
}

export function formatRelativeTime(uts?: number): string {
    if (!uts) return 'Recently';
    const now = Math.floor(Date.now() / 1000);
    const diff = Math.max(0, now - uts);

    if (diff < 60) return 'Just now';
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    const days = Math.floor(diff / 86400);
    if (days < 30) return `${days}d ago`;
    return new Date(uts * 1000).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

export function useLastFm(_limit: number = 9): LastFmData {
    const [currentTrack, setCurrentTrack] = useState<LastFmTrack | null>(null);
    const [recentTracks, setRecentTracks] = useState<LastFmTrack[]>([]);
    const [totalScrobbles, setTotalScrobbles] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    const fetchTracks = useCallback(async () => {
        try {
            // Fetch the static snapshot generated by GitHub Actions
            const response = await fetch(`/lastfm.json?t=${Date.now()}`);
            if (!response.ok) {
                throw new Error(`Failed to load music activity (${response.status})`);
            }

            const data = await response.json();

            const parsedCurrent: LastFmTrack | null = data.currentTrack
                ? {
                      ...data.currentTrack,
                      timeAgo: data.currentTrack.nowPlaying
                          ? 'Now Playing'
                          : formatRelativeTime(data.currentTrack.timestamp),
                  }
                : null;

            const parsedRecent: LastFmTrack[] = (data.recentTracks || []).map((t: LastFmTrack) => ({
                ...t,
                timeAgo: formatRelativeTime(t.timestamp),
            }));

            setCurrentTrack(parsedCurrent);
            setRecentTracks(parsedRecent);
            if (data.totalScrobbles) {
                setTotalScrobbles(data.totalScrobbles);
            }

            setError(null);
        } catch (err: any) {
            console.error('Failed to load Last.fm data:', err);
            setError(err?.message || 'Failed to load music activity');
        } finally {
            setIsLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchTracks();

        // Check for updates every 20 seconds
        const interval = setInterval(() => {
            fetchTracks();
        }, 20000);

        return () => clearInterval(interval);
    }, [fetchTracks]);

    return {
        currentTrack,
        recentTracks,
        totalScrobbles,
        isLoading,
        error,
        isNowPlaying: !!currentTrack?.nowPlaying,
        refresh: fetchTracks,
    };
}
